name: NMLWeapons
version: '1'
main: io.github.Gabriel.nMLWeapons.NMLWeapons
api-version: '1.21.8'
authors: [ Gabriel Nicolas ]
depend:
  - NMLPlayerStats
  - DamagePlugin
  - NMLItems
  - ExpertiseStylePlugin
commands:
  generateWeapon:
    description: generates a weapon for the player
    usage: /<command> <type> <rarity>