name: NMLWeapons
version: '1.0'
main: io.github.NoOne.nMLWeapons.NMLWeapons
api-version: '1.21'
depend:
  - NMLPlayerStats
  - DamagePlugin
  - NMLItems
  - ExpertiseStylePlugin
  - NMLSkills
  - ProtocolLib
commands:
  generateWeapon:
    description: generates a weapon for the player
    usage: /<command> <type> <rarity>